// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCON-uStQHa6gm0X6K15VkhwmlZHPqlnlo',
    appId: '1:520037154879:web:83e41196b339780bb2388a',
    messagingSenderId: '520037154879',
    projectId: 'nofakenews-301c5',
    authDomain: 'nofakenews-301c5.firebaseapp.com',
    storageBucket: 'nofakenews-301c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkJvXODxjheXtfEYeWDDvx455VuOoo9wU',
    appId: '1:520037154879:android:e7edf55fbb8c375cb2388a',
    messagingSenderId: '520037154879',
    projectId: 'nofakenews-301c5',
    storageBucket: 'nofakenews-301c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkytySxIjgHxjIHbWk7HYpT8aHdUl3mJg',
    appId: '1:520037154879:ios:67c893a29cbea63cb2388a',
    messagingSenderId: '520037154879',
    projectId: 'nofakenews-301c5',
    storageBucket: 'nofakenews-301c5.firebasestorage.app',
    iosBundleId: 'com.example.veritasAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkytySxIjgHxjIHbWk7HYpT8aHdUl3mJg',
    appId: '1:520037154879:ios:67c893a29cbea63cb2388a',
    messagingSenderId: '520037154879',
    projectId: 'nofakenews-301c5',
    storageBucket: 'nofakenews-301c5.firebasestorage.app',
    iosBundleId: 'com.example.veritasAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCON-uStQHa6gm0X6K15VkhwmlZHPqlnlo',
    appId: '1:520037154879:web:922094e96df9b61db2388a',
    messagingSenderId: '520037154879',
    projectId: 'nofakenews-301c5',
    authDomain: 'nofakenews-301c5.firebaseapp.com',
    storageBucket: 'nofakenews-301c5.firebasestorage.app',
  );
}
